# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-01 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('file_file', models.FileField(upload_to='upload/', verbose_name='文件路径')),
                ('file_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_delete', models.BooleanField(default=False)),
                ('file_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
