# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-03 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_share',
            field=models.BooleanField(default=False, verbose_name='文件共享'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_delete',
            field=models.BooleanField(default=False, verbose_name='文件删除'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_file',
            field=models.FileField(upload_to=user.models.user_directory_path, verbose_name='文件路径'),
        ),
    ]
