# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-06 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190403_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpro',
            name='person',
            field=models.TextField(max_length=1024, null=True, verbose_name='个人信息'),
        ),
    ]
