# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-06 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userpro_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('0', '女')], default='男', max_length=32),
        ),
    ]
