# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-07 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190406_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_classify',
            field=models.CharField(choices=[('教学资源', 'one'), ('课程内容', 'two'), ('学生作业', 'three'), ('普通文档', 'four'), ('其他文档', 'five')], default='four', max_length=32, verbose_name='文件分类'),
        ),
        migrations.AddField(
            model_name='files',
            name='file_format',
            field=models.CharField(max_length=32, null=True, verbose_name='文件格式'),
        ),
    ]
