# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-07 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190407_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='sex',
            field=models.CharField(choices=[('男', '1'), ('女', '0')], default='1', max_length=32),
        ),
    ]
