# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-08 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190407_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['file_time'], 'verbose_name': '所有文档', 'verbose_name_plural': '所有文档'},
        ),
        migrations.AlterModelOptions(
            name='userpro',
            options={'ordering': ['date_joined'], 'verbose_name': '所有用户', 'verbose_name_plural': '所有用户'},
        ),
        migrations.AddField(
            model_name='files',
            name='file_downloads',
            field=models.IntegerField(default=0, verbose_name='下载次数'),
        ),
    ]
